### ISSUE TITLE
 give more info

### ISSUE THREAD

**Issue by doubleTroub1e** [shvqn/tools#11]
Hi again, I 've start some of tappers, and would like to start some more but faced issues:
1) Cybase
- don't know how to get data needed for this, this is not a pure query_id extracted from get requests or from Application Init_data devtools

2) nomis
- can't find data needed, this is query_id but with some chat info, not sure where to take it
- no package*.json 
I'm using Dockerfiles, pretty simple one, like this:
```
FROM node:20.10.0-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
CMD [ "node", "nomis.js" ]
``` 

3) coinegg

- I've start it fine with query ID but saw errors in logs
```
coinegg  | [#] Account 1 | Login...
coinegg  | [#] Account 1 | Balance: 0 💎, 0 🥚, 0 💲
coinegg  | [#] Account 1 | Đã nhặt 1134 🥚
coinegg  | [#] Account 1 | Đã nhặt 0.07 💲
coinegg  | Main Err: TypeError: Cannot read properties of undefined (reading 'id')
coinegg  | Run next at: 17:09:23
coinegg  | [#] Account 1 | Đã nhặt 758 🥚
coinegg  | [#] Account 1 | Đã nhặt 279 🥚
``` 

probably not important..

4) arix 
- you've missed adding ref for it, so will wait for that 
- also not sure how to extract those data needed from Chrome devtools, can you please add some small screenshot or small guide on how to

Thank you very much for work done!

also, if searching new projects to create automation for here is list:
1) [Wuffitap](https://t.me/Wuffitap_Bot/wuffitap?startapp=r_595909481). - pretty good one as meme token on 2 blockchaines: WAX and solana, I've manage to claim WAX holders drop of wuff, and it was about 50$ that time, and 500$ in 2 weeks
2) [NOTAI_App](https://t.me/NOTAI_App_Bot/notai?startapp=qN2nnKaASqAragA) very fresh project, know almost nothing about  it since pretty new one

**Comment by shvqn** [comment]
1. I use iframe for most of my tools because it's simpler to extract. You just need to paste this line into the devtools console to extract it: document.querySelector('iframe').
2. Input file of nomis is id.txt: user_id|username. You can use the file tach.js to export the file id.txt from the input data of other projects.
3. That is a minor bug that does not affect the tool's operation. I will fix it later

Final, can u add the links of projects u suggested?

**Comment by doubleTroub1e** [comment]
hi, sure
 wuffi -> https://www.wuffi.io/ off site, my ref: https://t.me/Wuffitap_Bot/wuffitap?startapp=r_595909481
 
 notAI -> off twitter https://x.com/theNOTAI.  ; my ref: https://t.me/NOTAI_App_Bot/notai?startapp=qN2nnKaASqAragA
